# Day 13 - NumPy Data Filtering

## Objective
Use NumPy conditions to identify values that are above, below, or equal to a specified threshold.

## Tools
- Python
- NumPy
- Jupyter Notebook

In [1]:
import numpy as np

In [2]:
marks = np.array([45, 67, 89, 32, 76, 54, 91, 38, 82, 60])

print("Student Marks:")
print(marks)

Student Marks:
[45 67 89 32 76 54 91 38 82 60]


In [3]:
above_50 = marks > 50

print("Boolean condition:")
print(above_50)

Boolean condition:
[False  True  True False  True  True  True False  True  True]


In [4]:
filtered_above_50 = marks[marks > 50]

print("Marks above 50:")
print(filtered_above_50)

Marks above 50:
[67 89 76 54 91 82 60]


In [5]:
marks[marks > 50]

array([67, 89, 76, 54, 91, 82, 60])

In [6]:
below_50 = marks[marks < 50]

print("Marks below 50:")
print(below_50)

Marks below 50:
[45 32 38]


In [7]:
equal_60 = marks[marks == 60]

print("Marks equal to 60:")
print(equal_60)

Marks equal to 60:
[60]


In [8]:
high_marks = marks[marks >= 75]

print("Marks greater than or equal to 75:")
print(high_marks)

Marks greater than or equal to 75:
[89 76 91 82]


In [9]:
medium_marks = marks[(marks >= 50) & (marks <= 80)]

print("Marks between 50 and 80:")
print(medium_marks)

Marks between 50 and 80:
[67 76 54 60]


In [11]:
(marks >= 50) & (marks <= 80)

array([False,  True, False, False,  True,  True, False, False, False,
        True])

## Sales Data Filtering

In [12]:
sales = np.array([1200, 850, 1500, 650, 2200, 950, 1800, 500])

print("Sales values:")
print(sales)

Sales values:
[1200  850 1500  650 2200  950 1800  500]


In [13]:
high_sales = sales[sales > 1000]

print("Sales above 1000:")
print(high_sales)

Sales above 1000:
[1200 1500 2200 1800]


In [14]:
low_sales = sales[sales < 1000]

print("Sales below 1000:")
print(low_sales)

Sales below 1000:
[850 650 950 500]


In [15]:
medium_sales = sales[(sales >= 800) & (sales <= 1800)]

print("Sales between 800 and 1800:")
print(medium_sales)

Sales between 800 and 1800:
[1200  850 1500  950 1800]


# Interview Questions

### 1. What is Boolean indexing?

Boolean indexing is a NumPy technique used to select elements from an array based on a condition.

### 2. How do you filter a NumPy array?

A NumPy array can be filtered by placing a Boolean condition inside square brackets.

Example:

`data[data > 50]`

### 3. What is a Boolean array?

A Boolean array contains `True` and `False` values based on whether each element satisfies a condition.

### 4. How do you apply multiple conditions in NumPy?

The `&` operator is used for AND conditions and the `|` operator is used for OR conditions.

### 5. What is Boolean indexing useful for?

Boolean indexing is useful for filtering and selecting specific data from NumPy arrays.